Updating Bash and Vim configuration files.

diff --git a/resources/bashrc b/resources/bashrc
--- a/resources/bashrc
+++ b/resources/bashrc
@@ -1,26 +1,35 @@
-# Bash aliases
+# Bash aliases.
 alias la='ls -a'
 alias ll='ls -l'
-alias l='ls -CF'
-
-if [ -f ~/.bash_aliases ]; then
-    . ~/.bash_aliases
-fi
-
-# Prompts
-if [ -f ~/.bash_prompt ]; then
-    . ~/.bash_prompt
-fi
+alias sd='. devel/setup.bash'
 
 if [ -f ~/.git-prompt.sh ]; then
     . ~/.git-prompt.sh
 fi
 
-# ROS
-export ROSCONSOLE_FORMAT='[${severity}] - ${node}:${line}: [${time}] ${message}'
-alias catkin_coverage='catkin_make -DCMAKE_CXX_FLAGS="-Wall -Wno-unused --coverage -fno-inline -fno-inline-small-functions -fno-default-inline" -DCMAKE_C_FLAGS="-Wall -Wno-unused --coverage -fno-inline -fno-inline-small-functions -fno-default-inline" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS="-lgcov"'
+if [ -f ~/.bash_prompt ]; then
+    . ~/.bash_prompt
+fi
+alias ls='ls --color'
+LS_COLORS='di=1;34'
+export LS_COLORS
 
-# Python notebooks
+# Core dumping.
+ulimit -c unlimited
+
+# ROS workspaces.
+. /opt/ros/melodic/setup.bash
+
+# ROS master.
+export ROS_MASTER_URI=http://localhost:11311
+export ROSCONSOLE_CONFIG_FILE=/home/$USER/.ros/rosconsole.config
+export ROSCONSOLE_FORMAT='[${severity}] [${time}] - ${node}:${function}:${line}: ${message}'
+export ROSLAUNCH_SSH_UNKNOWN=1
+
+alias catkin_coverage_setup='catkin config --cmake-args -DCMAKE_CXX_FLAGS="-Wall -Wno-unused --coverage -fno-inline -fno-inline-small-functions -fno-default-inline" -DCMAKE_C_FLAGS="-Wall -Wno-unused --coverage -fno-inline -fno-inline-small-functions -fno-default-inline" -DCMAKE_BUILD_TYPE=Debug'
+alias catkin_config_clang_sanitizer='catkin config --cmake-args -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 -DCMAKE_C_FLAGS="-O1 -g -fsanitize=address -fno-omit-frame-pointer" -DCMAKE_CXX_FLAGS="-O1 -g -fsanitize=address -fno-omit-frame-pointer"'
+
+# For Jupyter notebooks and version control.
 alias nbstrip_jq="jq --indent 1 \
     '(.cells[] | select(has(\"outputs\")) | .outputs) = []  \
     | (.cells[] | select(has(\"execution_count\")) | .execution_count) = null  \
@@ -34,3 +43,18 @@ function nbstrip_all_cwd {
     done
     unset nbfile
 }
+
+# enable bash completion in interactive shells
+if ! shopt -oq posix; then
+  if [ -f /usr/share/bash-completion/bash_completion ]; then
+    . /usr/share/bash-completion/bash_completion
+  elif [ -f /etc/bash_completion ]; then
+    . /etc/bash_completion
+  fi
+fi
+
+# https://askubuntu.com/questions/22413/how-to-change-gnome-terminal-title
+termtitle() { printf "\033]0;$*\007"; }
+
+# https://stackoverflow.com/questions/39829230/git-does-not-ask-me-for-gpg-passphrase-and-fails-my-commit
+export GPG_TTY=$(tty)
